// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7y2w89kN13eh89hVsUXMKgXWw-1HsBw',
    appId: '1:483621465996:web:4729ae9a61ada92087f0a9',
    messagingSenderId: '483621465996',
    projectId: 'chatappflutter-55b10',
    authDomain: 'chatappflutter-55b10.firebaseapp.com',
    storageBucket: 'chatappflutter-55b10.firebasestorage.app',
    measurementId: 'G-GT8QBKBPVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBow5cc5SqHqF91IYConZaG0ptRTdq8HmA',
    appId: '1:483621465996:android:53158ddd9c653a7b87f0a9',
    messagingSenderId: '483621465996',
    projectId: 'chatappflutter-55b10',
    storageBucket: 'chatappflutter-55b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC67kjmPQdX1TzrOcLo9wUxOchxIgJ_bH8',
    appId: '1:483621465996:ios:5bf4c98b221b134487f0a9',
    messagingSenderId: '483621465996',
    projectId: 'chatappflutter-55b10',
    storageBucket: 'chatappflutter-55b10.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC67kjmPQdX1TzrOcLo9wUxOchxIgJ_bH8',
    appId: '1:483621465996:ios:5bf4c98b221b134487f0a9',
    messagingSenderId: '483621465996',
    projectId: 'chatappflutter-55b10',
    storageBucket: 'chatappflutter-55b10.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk7y2w89kN13eh89hVsUXMKgXWw-1HsBw',
    appId: '1:483621465996:web:691f5902cfa2635687f0a9',
    messagingSenderId: '483621465996',
    projectId: 'chatappflutter-55b10',
    authDomain: 'chatappflutter-55b10.firebaseapp.com',
    storageBucket: 'chatappflutter-55b10.firebasestorage.app',
    measurementId: 'G-RYC0VSE6Z8',
  );
}
